export const sampleEventList = [
   {
      id: 1,
      name: 'Tango Siesta',
      startDate: '2019-07-14',
      endDate: '2019-08-18',
      country: 'Turkey',
      city: "",
      registrationCurrency: "",
      registrationFee: 0,
      noNeedTransport: false,
      originCity: "",
      transportOption: "",
      transportCosts: 0,
      noNeedAccommodation: false,
      numOfPersons: 1,
      accommodationOption: "",
      accommodationCosts: 0,
      currency: "EUR",
      additionalCosts: 0,
      totalCosts: 0,
      notes: "",
      firstDot: true,
      secondDot: true,
      thirdDot: true,
      fourthDot: false
   },
   {
      id: 2,
      name: 'Bg Workshops',
      startDate: '2019-09-05',
      endDate: '2019-09-10',
      country: 'Serbia',
      city: "",
      registrationCurrency: "",
      registrationFee: 0,
      originCity: "",
      transportOption: "",
      transportCosts: 0,
      numOfPersons: 1,
      accommodationOption: "",
      accommodationCosts: 0,
      currency: "EUR",
      additionalCosts: 0,
      totalCosts: 0,
      notes: "",
      firstDot: true,
      secondDot: false,
      thirdDot: false,
      fourthDot: false
   },
   {
      id: 3,
      name: 'Pippo & Friends',
      startDate: '2019-10-25',
      endDate: '2019-10-28',
      country: "",
      city: "",
      registrationCurrency: "",
      registrationFee: 0,
      originCity: "",
      transportOption: "",
      transportCosts: 0,
      numOfPersons: 1,
      accommodationOption: "",
      accommodationCosts: 0,
      currency: "EUR",
      additionalCosts: 0,
      totalCosts: 0,
      notes: "",
      firstDot: true,
      secondDot: true,
      thirdDot: false,
      fourthDot: false
   },
   {
      id: 4,
      name: 'JS Meetup',
      startDate: '2019-12-22',
      endDate: '2019-12-25',
      country: "",
      city: "",
      registrationCurrency: "",
      registrationFee: 0,
      originCity: "",
      transportOption: "",
      transportCosts: 0,
      numOfPersons: 1,
      accommodationOption: "",
      accommodationCosts: 0,
      currency: "EUR",
      additionalCosts: 0,
      totalCosts: 0,
      notes: "",
      firstDot: false,
      secondDot: false,
      thirdDot: false,
      fourthDot: false
   }
]